# Generated by Django 3.0.5 on 2020-04-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default=None, max_length=64)),
                ('car_model', models.CharField(default=None, max_length=64)),
                ('production_year', models.IntegerField(default=1900, max_length=4)),
                ('transmission', models.SmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')], default=1, max_length=1)),
                ('car_color', models.CharField(default=None, max_length=64)),
            ],
        ),
    ]
